version: "3.8"

services:
  app:
    container_name: react-app-prod
    image: react-app-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
